
CREATE TABLE [dbo].[Contacts](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProspectId] [int] NULL,
	[IsPrimary] [bit] NULL,
	[FirstName] [varchar](100) NULL,
	[MiddleName] [varchar](100) NULL,
	[LastName] [varchar](100) NULL,
	[JobTitle] [varchar](100) NULL,
	[IsAddressSameAsProspect] [bit] NULL,
	[IsNpsNominated] [bit] NULL,
	[Home1AddressTitle] [varchar](100) NULL,
	[Home1AddressLine1] [varchar](100) NULL,
	[Home1AddressLine2] [varchar](100) NULL,
	[Home1City] [varchar](100) NULL,
	[Home1State] [varchar](100) NULL,
	[Home1ZipCode] [varchar](100) NULL,
	[Home1PhoneNumber] [varchar](100) NULL,
	[Home1Email] [varchar](100) NULL,
	[Home1Extension] [varchar](100) NULL,
	[Home1Fax] [int] NULL,
	[Home2Address_Title] [varchar](100) NULL,
	[Home2AddressLine1] [varchar](100) NULL,
	[Home2AddressLine2] [varchar](100) NULL,
	[Home2City] [varchar](100) NULL,
	[Home2State] [varchar](100) NULL,
	[Home2ZipCode] [varchar](100) NULL,
	[Home2PhoneNumber] [varchar](100) NULL,
	[Home2Email] [varchar](100) NULL,
	[Home2Extension] [varchar](10) NULL,
	[Home2Fax] [int] NULL,
	[Office1AddressTitle] [varchar](100) NULL,
	[Office1AddressLine1] [varchar](100) NULL,
	[Office1AddressLine2] [varchar](100) NULL,
	[Office1City] [varchar](100) NULL,
	[Office1State] [varchar](100) NULL,
	[Office1ZipCode] [varchar](100) NULL,
	[Office1PhoneNumber] [varchar](100) NULL,
	[Office1Email] [varchar](100) NULL,
	[Office1Extension] [varchar](100) NULL,
	[Office1Fax] [int] NULL,
	[Office2AddressTitle] [varchar](100) NULL,
	[Office2AddressLine1] [varchar](100) NULL,
	[Office2AddressLine2] [varchar](100) NULL,
	[Office2City] [varchar](100) NULL,
	[Office2State] [varchar](100) NULL,
	[Office2ZipCode] [varchar](100) NULL,
	[Office2PhoneNumber] [varchar](100) NULL,
	[Office2Email] [varchar](100) NULL,
	[Office2Extension] [varchar](100) NULL,
	[Office2Fax] [int] NULL,
	[CreatedDateTime] [datetime] NULL,
	[ModifiedDateTime] [datetime] NULL,
	[CreatedBy] [varchar](100) NULL,
	[ModifiedBy] [varchar](100) NULL,
	[IsDeleted] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
